service_account_name = "example-service-account"
service_account_path = "example-terraform"
GITHUB_REPOSITORY_OWNER = "sim-parables"
GITHUB_REPOSITORY = "sim-parables/terraform-aws-blob-trigger"
GITHUB_REF = "refs/head/main"
GITHUB_ENV = "production"